# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        make install
      env:
        CI: true
    - name: Run linter
      run: |
        make lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
     #33e71e645415d7c0c1621ad7d79c8363b42dfc08d922f3efe94b8b102012bf75: ${{secrets.33e71e645415d7c0c1621ad7d79c8363b42dfc08d922f3efe94b8b102012bf75}}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true
  
